# Generated by Django 4.1 on 2022-09-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/chatroom/discord/static/images/avatar.svg', null=True, upload_to='profile_avatar'),
        ),
    ]
